#!/usr/bin/env python3
#
# Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
#
# SPDX-License-Identifier: BSD-3-Clause
#
#
# Little script to build a header file including every other header file in the SDK!
# (also checks we don't have "conflicting" header-filenames)
# Edit the IGNORE_DIRS variable to filter out which directories get looked in.
#
# Usage:
#
# tools/build_all_headers.py <root of source tree> <output file> --ignore <optional path 1> <optional path 2/**> ...

import os
import sys
import fnmatch

# Add as neccessary, or pass with the optional --ignore
# globs like 'rp2350/**' also work
IGNORE_DIRS = set([
    'host', 'boards',
    'common/boot_picoboot',
    'common/boot_uf2',
    'common/pico_usb_reset_interface',
    'rp2_common/cmsis',
    'rp2_common/pico_async_context',
    'rp2_common/pico_btstack',
    'rp2_common/pico_cyw43_arch',
    'rp2_common/pico_cyw43_driver',
    'rp2_common/pico_lwip',
    'rp2_common/pico_stdio_semihosting',
    'rp2_common/pico_stdio_usb'
])

if '--ignore' in sys.argv:
    idx = sys.argv.index('--ignore')
    user_provided_ignores = sys.argv[idx + 1:]
    sys.argv = sys.argv[:idx]
    IGNORE_DIRS.update(user_provided_ignores)

if len(sys.argv) != 3:
    print("Usage: {} top_dir output_header".format(os.path.basename(sys.argv[0])))
    sys.exit(1)

top_dir = os.path.join(sys.argv[1], 'src')
output_header = sys.argv[2]

if not os.path.isdir(top_dir):
    print("{} doesn't exist!".format(top_dir))
    sys.exit(1)

include_dirs = set()
for root, dirs, files in os.walk(top_dir):
    prune_dirs = []
    for d in dirs:
        rel_path = os.path.relpath(os.path.join(root, d), top_dir)

        # Check against all glob patterns:
        if any(fnmatch.fnmatch(rel_path, pat) for pat in IGNORE_DIRS):
            prune_dirs.append(d)
    for d in prune_dirs:
        dirs.remove(d)

    if 'include' in dirs:
        include_dirs.add(os.path.join(root, 'include'))
        dirs.remove('include')

include_files = list()
include_locations = dict()
for d in sorted(include_dirs):
    for root, dirs, files in os.walk(d):
        for f in sorted(files):
            if f.endswith('.h'):
                include_file = os.path.relpath(os.path.join(root, f), d)
                include_path = os.path.relpath(d, top_dir)
                if include_file in include_files:
                    raise Exception("Duplicate include file '{}' (found in both {} and {})".format(include_file, include_locations[include_file], include_path))
                include_files.append(include_file)
                include_locations[include_file] = include_path

with open(output_header, 'w') as fh:
    fh.write('''/*
 * Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// This file is autogenerated, do not edit by hand

''')
    last_location = ''
    for f in include_files:
        if include_locations[f] != last_location:
            fh.write('\n// {}\n'.format(include_locations[f]))
        fh.write('#include "{}"\n'.format(f))
        last_location = include_locations[f]
    fh.write('\n')

