#!/usr/bin/env python3
#
# Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
#
# SPDX-License-Identifier: BSD-3-Clause
#
#
# Little script to build a header file including every other header file in the SDK!
# (also checks we don't have "conflicting" header-filenames)
# Edit the IGNORE_DIRS variable to filter out which directories get looked in.
#
# Usage:
#
# tools/build_all_headers.py <root of source tree> <output file> --ignore <optional path 1> <optional path 2/**> ...

import os
import sys
import fnmatch

# Add as neccessary, or pass with the optional --ignore
# globs like 'rp2350/**' also work
IGNORE_DIRS = set([
    'host', 'boards',
    'common/boot_picoboot',
    'common/boot_uf2',
    'common/pico_usb_reset_interface',
    'rp2_common/cmsis',
    'rp2_common/pico_async_context',
    'rp2_common/pico_btstack',
    'rp2_common/pico_cyw43_arch',
    'rp2_common/pico_cyw43_driver',
    'rp2_common/pico_lwip',
    'rp2_common/pico_stdio_semihosting',
    'rp2_common/pico_stdio_usb'
])

if '--ignore' in sys.argv:
    idx = sys.argv.index('--ignore')
    user_provided_ignores = sys.argv[idx + 1:]
    sys.argv = sys.argv[:idx]
    IGNORE_DIRS.update(user_provided_ignores)


SORT_HEADERS_BY_DIRECTORY = True # if False, sort by filename

if len(sys.argv) != 3:
    print("Usage: {} top_dir output_header".format(os.path.basename(sys.argv[0])))
    sys.exit(1)

top_dir = os.path.join(sys.argv[1], 'src')
output_header = sys.argv[2]

if not os.path.isdir(top_dir):
    print("{} doesn't exist!".format(top_dir))
    sys.exit(1)

include_dirs = set()
for root, dirs, files in os.walk(top_dir):
    prune_dirs = []
    for d in dirs:
        rel_path = os.path.relpath(os.path.join(root, d), top_dir)

        # Check against all glob patterns:
        if any(fnmatch.fnmatch(rel_path, pat) for pat in IGNORE_DIRS):
            prune_dirs.append(d)
    for d in prune_dirs:
        dirs.remove(d)

    if 'include' in dirs:
        include_dirs.add(os.path.join(root, 'include'))
        dirs.remove('include')

include_files_by_chip = {
    'none': list(),
    'rp2040': list(),
    'rp2350': list(),
}
all_include_files = set()
include_locations = dict()
for d in sorted(include_dirs):
    for root, dirs, files in os.walk(d):
        for f in sorted(files):
            if f.endswith('.h'):
                include_file = os.path.relpath(os.path.join(root, f), d)
                include_path = os.path.relpath(d, top_dir)
                if 'rp2040/' in include_path:
                    include_files_by_chip['rp2040'].append(include_file)
                elif 'rp2350/' in include_path:
                    include_files_by_chip['rp2350'].append(include_file)
                else:
                    if include_file in include_files_by_chip['none']:
                        raise Exception("Duplicate include file '{}' (found in both {} and {})".format(include_file, include_locations[include_file], include_path))
                    include_files_by_chip['none'].append(include_file)
                include_locations[include_file] = include_path
                all_include_files.add(include_file)

# figure out which includes are applicable to both chips
include_files_by_chip['both'] = []
for f in include_files_by_chip['rp2040']:
    if f in include_files_by_chip['rp2350']:
        include_files_by_chip['both'].append(f)
        include_locations[f] = include_locations[f].replace('rp2350/', 'rp2xxx/')
for f in include_files_by_chip['both']:
    include_files_by_chip['rp2040'].remove(f)
    include_files_by_chip['rp2350'].remove(f)

if SORT_HEADERS_BY_DIRECTORY:
    with open(output_header, 'w') as fh:
        fh.write('''/*
 * Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// This file is autogenerated, do not edit by hand

''')
        last_location = ''
        for f in include_files_by_chip['none']:
            if include_locations[f] != last_location:
                fh.write('\n// {}\n'.format(include_locations[f]))
            fh.write('#include "{}"\n'.format(f))
            last_location = include_locations[f]
        for f in include_files_by_chip['both']:
            if include_locations[f] != last_location:
                fh.write('\n// {}\n'.format(include_locations[f]))
            fh.write('#include "{}"\n'.format(f))
            last_location = include_locations[f]
        if include_files_by_chip['rp2040']:
            fh.write('\n#if PICO_RP2040\n')
            for f in include_files_by_chip['rp2040']:
                if include_locations[f] != last_location:
                    fh.write('\n// {}\n'.format(include_locations[f]))
                fh.write('#include "{}"\n'.format(f))
                last_location = include_locations[f]
            fh.write('\n#endif\n')
        if include_files_by_chip['rp2350']:
            fh.write('\n#if PICO_RP2350\n')
            for f in include_files_by_chip['rp2350']:
                if include_locations[f] != last_location:
                    fh.write('\n// {}\n'.format(include_locations[f]))
                fh.write('#include "{}"\n'.format(f))
                last_location = include_locations[f]
            fh.write('\n#endif\n')
        fh.write('\n')
else:
    with open(output_header, 'w') as fh:
        fh.write('''/*
 * Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// This file is autogenerated, do not edit by hand

''')
        last_define = None
        for f in sorted(all_include_files, key=lambda x: os.path.split(x)):
            if f in include_files_by_chip['rp2040']:
                define = 'PICO_RP2040'
            elif f in include_files_by_chip['rp2350']:
                define = 'PICO_RP2350'
            else:
                define = None
            if define != last_define:
                if last_define is not None:
                    fh.write('#endif\n')
                if define is not None:
                    fh.write('#if {}\n'.format(define))
            fh.write('#include "{}"\n'.format(f))
            last_define = define
        if last_define is not None:
            fh.write('#endif\n')
        fh.write('\n')

